# Generated by Django 5.1.4 on 2024-12-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_pannel', '0002_alter_adminmodel_options_alter_adminmodel_mobile_no_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_math', 'General Math'), ('bangla', 'Bangla'), ('english', 'English'), ('general_science', 'General Science'), ('religion', 'Religion'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('higher_math', 'Higher Math'), ('all_subjects', 'All Subjects')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tuition_class', models.CharField(blank=True, choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3'), ('class_4', 'Class 4'), ('class_5', 'Class 5'), ('class_6', 'Class 6'), ('class_7', 'Class 7'), ('class_8', 'Class 8'), ('class_9', 'Class 9'), ('class_10', 'Class 10'), ('hsc_1', 'HSC 1st Year'), ('hsc_2', 'HSC 2nd Year')], max_length=50, null=True)),
                ('availability', models.BooleanField(default=True, help_text='Availability status of the tuition')),
                ('description', models.TextField(blank=True, help_text='Detailed Description of the tuition', null=True)),
                ('medium', models.CharField(blank=True, choices=[('bangla', 'Bangla Medium'), ('english', 'English Version')], help_text='Medium of instruction', max_length=50, null=True)),
                ('student_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('tutor_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Preferred gender of tutor', max_length=1, null=True)),
                ('tutoring_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], help_text='Time for tutoring', max_length=20, null=True)),
                ('number_of_students', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Salary offered per month', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('tutoring_experience', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='admin_pannel.adminmodel')),
                ('subjects', models.ManyToManyField(blank=True, related_name='tuitions', to='tutor.subjectchoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='student.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tutor.tutor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
