# Generated by Django 5.1.4 on 2024-12-13 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0002_alter_adminmodel_options_alter_adminmodel_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='mobile_no',
            field=models.CharField(help_text='Contact phone number in Bangladesh format (+8801XXX)', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801234567890'", regex='^\\+?88[0-9]{11}$')]),
        ),
    ]
