# Generated by Django 5.1.4 on 2024-12-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('applied', 'Applied'), ('accepted', 'Accepted')], default='applied', max_length=20, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False, help_text='Indicates if the application has been cancelled')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tutor.tutor')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
